//############################################################################//
// Orulex: Dynamic planet default cfg's
// Released under GNU General Public License
// Made in 2006-2010 by Artyom Litvinovich
//############################################################################//
 lrndseed:=65774;

 ocfg.maxpolycount:=128000;
 ocfg.balancing_time_slice:=1000;
 ocfg.main_queue_time_slice:=8000;
 ocfg.priorities_time_slice:=1000;
 ocfg.textures_time_slice:=50000;
 ocfg.levlimit:=17;
 ocfg.global_heightmap_limit:=8;
 ocfg.texture_range_factor:=2.1;
 ocfg.texture_gen_order:=1;
 ocfg.multithreaded:=true;
 ocfg.hmapdir:='heightmaps';
 ocfg.texdir :='textures';
 ocfg.cfgdir :='config'+ch_slash+'terrain';
 ocfg.bcfgdir:='config';
 ocfg.texture_res:=65;//33;
//############################################################################//

